apiVersion: v1
kind: Service
metadata:
  name: feature-test-service
  namespace: default
spec:
  selector:
    app: feature-test-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

